name: StairSeat
api: 3.14.0
main: korado531m7\StairSeat\StairSeat
version: 1.5.7
author: korado531m7
description: Enable to sit on the stair block
mcpe-protocol: 428
permissions:
  stairseat.toggle:
    description: "Toggle to sit"
    default: true
